### ISSUE TITLE
[bug] API Test page

### ISSUE THREAD

**Issue by safe-tvigil** [Cale-Torino/FreeTAKServer_Manager#1]
On the app it looks like the local test and custom test buttons are switched around. The app is also not working with the FTS v1.8

Please let us know when this will be fixed.

**Comment by Cale-Torino** [comment]
This app was intended for experimental implementations. At the moment the `FTS` code is changing every month and new and exciting features are being added so it will be hard to get a stable up to date version.

I will keep your company up to date on Skype.

The Linux implementation is the recommended way to host the server so perhaps we can explore that avenue.
