### ISSUE TITLE
NEW ISSUE

### ISSUE THREAD

**Issue by Lex327-liu** [Cale-Torino/FreeTAKServer_Manager#6]
Thank you for your contributions, I've learned a lot from git and youtube. But I still have a problem and I need your help. where can I download freetakserver.exe?  I didn't find it on github (sorry, I'm a noob).

**Comment by Cale-Torino** [comment]
Hi. the installer and portable .exe are located under [releases](https://github.com/Cale-Torino/FreeTAKServer_Manager/releases)

**Comment by Lex327-liu** [comment]
Wow, thanks a lot! I can go in now. But there is still a small problem, webmap shows that 127.0.0.1 has been rejected, do you know how to solve it?

**Comment by Lex327-liu** [comment]
And how do I connect to ATAK on Android? I tried to set up a tcp connection but couldn't load zip at select server

**Comment by Cale-Torino** [comment]
The _webmap_ must be installed on another machine then you can include the IP in the FTS config file.

<img width="161" alt="image" src="https://github.com/Cale-Torino/FreeTAKServer_Manager/assets/52330180/478092f0-07c6-4aff-88cf-5cf31ff14004">

If you use port `8087` in ATAK then you don't need any certs. Only **SSL** uses port `8089` with certs.
