### ISSUE TITLE
Server Issue

### ISSUE THREAD

**Issue by TangoZuluMike** [Cale-Torino/FreeTAKServer_Manager#7]
Successfully began "Install Server" but it failed and gave: Error:Could not find a part of the path 'C:\Software\Python\Lib\site-packages\FreeTAKServer\FTSConfig.yaml'.

Running Python 3.11.4

**Comment by TangoZuluMike** [comment]
Edited config to specify python 3.11.4
Added \FreeTAKServer\FTSConfig.yaml'
Ran "Install Server" and got Error:Could not find a part of the path 'C:\Software\Python\Lib\site-packages\FreeTAKServer-UI\config.py'.

**Comment by TangoZuluMike** [comment]
Built out those files too.
Server installed successfully.

**Comment by TangoZuluMike** [comment]
Final problem 127.0.0.1 refuses to connect.

Command prompt windows read:

Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: Could not import 'run'.

C:\Software\Python\Lib\site-packages\FreeTAKServer-UI>

--- and ---

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Software\Python\Lib\site-packages\FreeTAKServer\controllers\services\FTS.py", line 1, in <module>
    from FreeTAKServer.core.persistence.DatabaseController import (
  File "C:\Software\Python\Lib\site-packages\FreeTAKServer\core\persistence\DatabaseController.py", line 11, in <module>
    from FreeTAKServer.core.configuration.DatabaseConfiguration import DatabaseConfiguration
  File "C:\Software\Python\Lib\site-packages\FreeTAKServer\core\configuration\DatabaseConfiguration.py", line 1, in <module>
    from FreeTAKServer.core.configuration.MainConfig import MainConfig
  File "C:\Software\Python\Lib\site-packages\FreeTAKServer\core\configuration\MainConfig.py", line 4, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

C:\Windows\System32>

**Comment by Cale-Torino** [comment]
Hi there what version of the `FreeTAKServer_Manager` are you using?

After selecting the `Python` path and saving it you can easily install or uninstall the FTS server files by clicking the relevant buttons.

As long as the path to `\site-packages` and no Python dependencies are missing all should be well.

Python installers I've tested on can be found [Python_Installer folder](https://github.com/Cale-Torino/FreeTAKServer_Manager/tree/main/Python_Installer)

**Comment by TangoZuluMike** [comment]
Thanks for getting back to me!

The manager should be the most recent version.

Python is 3.11.4, I've already changed the mainconfig to 3.11.4.

At this point, I think I've got it to start the server, I just can't access
it through my web browser. I'm attempting to troubleshoot it.
